name: trigger image refresh

# Run every night at midnight
on:
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update with current timestamp
        run: date +%F-%H-%M-%S > .trigger-ci
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: "cronjob: Automated image refresh trigger"
          commit_options: '--signoff'
          file_pattern: .trigger-ci
          skip_fetch: true
          commit_user_name: GitHub Actions
          commit_user_email: noreply@github.com
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          push_options: --force # Protected Branch

